# Publish the Nix flake outputs to Cachix

name: Cachix
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: thattomperson-nixvim
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Build nix flake
      run: nix build -L
